import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:frontend/constants/colors.dart' as appColors;
import 'package:frontend/models/noodl_model.dart';
import 'package:frontend/pages/login.dart';
import 'package:frontend/pages/user_noodls.dart';
import 'package:frontend/providers/metamask_provider.dart';
import 'package:frontend/services/services.dart';
import 'package:frontend/widgets/common/topbar.dart';
import 'package:frontend/widgets/home/empty_your_noodls.dart';
import 'package:frontend/widgets/home/generate_noodl_button.dart';
import 'package:frontend/widgets/home/heading_widget.dart';
import 'package:frontend/widgets/home/noodl_button.dart';
import 'package:frontend/widgets/home/view_all_noodls_button.dart';
import 'package:provider/provider.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    EdgeInsets dp = MediaQuery.of(context).padding;
    return Scaffold(
      backgroundColor: appColors.bgColor,
      body: Stack(
        children: [
          RefreshIndicator(
            edgeOffset: 100,
            displacement: 20,
            onRefresh: () => Navigator.of(context).pushReplacement(PageRouteBuilder(pageBuilder: (context, a1, a2) => HomePage(),transitionDuration: Duration.zero, reverseTransitionDuration: Duration.zero)),
            
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  SizedBox(height: dp.top + 60,),
                  SizedBox(height: 12,),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 12),
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // SizedBox(height: 12,),
                        FutureBuilder(
                          future: APIservice.getUserNoodls(
                            walletAdd: Provider.of<MetaMaskProvider>(context, listen: false).walletAddress!
                              // ??"0x718fafb76e1631f5945bf58104f3b81d9588819b",
                              // remove this
                            // walletAdd: Provider.of<MetaMaskProvider>(context, listen: false).walletAddress!,
                            ,limit: 2
                          ),
                          builder: (context, snapshot) {
                            return snapshot.hasData && (snapshot.data! as List).isNotEmpty?
                              Column(
                                mainAxisSize: MainAxisSize.min,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Row(
                                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      HeadingWidget(
                                        heading: 'Your Noodls',
                                        subHeading: 'Your learning paths appear here.'
                                      ),
                                      ViewAllNoodlsButton(
                                        onTap: () => Navigator.of(context).push(MaterialPageRoute(builder: (context) => UserNoodlsPage(),)),
                                      )
                                    ],
                                  ),
                                  ...snapshot.data.map((e)=>NoodlButton(data: e)),
                                  // ShowAllNoodlsButton()
                                ],
                              ) : Column(
                                mainAxisSize: MainAxisSize.min,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  HeadingWidget(
                                    heading: 'Your Noodls',
                                    subHeading: 'Your learning paths appear here.'
                                  ),
                                  EmptyYourNoodls(),
                                ],
                              );
                          },
                        ),
                        
                        // SizedBox(height: 12,),
                        GenerateNoodlButton(),
                        HeadingWidget(
                          heading: 'Community Noodls',
                          subHeading: 'Community Noodls refer to popular learning paths previously generated by other users.'
                        ),
                        FutureBuilder(
                          future: APIservice.getCommunityNoodls(),
                          builder: (context, snapshot) {
                            return snapshot.hasData?
                              Column(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  ...snapshot.data.map((e)=>NoodlButton(data: e)),
                                  SizedBox(height: 12,),
                                  Consumer<MetaMaskProvider>(
                                    builder: (context, provider, child) => 
                                    ViewAllNoodlsButton(
                                      text: "Logout",
                                      onTap: () {
                                        provider.disconnect();
                                        // Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (context) => LoginPage(),));
                                      },
                                    ),
                                  ),
                                  SizedBox(height: 12,),
                                ],
                              ) : CupertinoActivityIndicator();
                          },
                        )
                        // NoodlButton(
                        //   data: NoodlModel(createdAt: "createdAt", description: description, id: 1, title: title, totalLevels: 1),
                        //   title: '🚗 Driving License in India',
                        //   description: "A user-generated learning path about Driving License in India.",
                        // ),
                        // NoodlButton(
                        //   title: '🥮 How to bake a chocolate chip cake without oven?',
                        //   description: "A user-generated learning path about how to bake a chocolate chip cake without oven?.",
                        // ),
                        // NoodlButton(
                        //   title: '🏁 Things to consider before going to n\u00fcrburgring track.',
                        //   description: "A user-generated learning path about Things to consider before going to n\u00fcrburgring track..",
                        // ),
                        // NoodlButton(
                        //   title: '🌱 How is Photosynthesis done?',
                        //   description: "A user-generated learning path about How is Photosynthesis done?.",
                        // ),
                        // NoodlButton(
                        //   title: '🏎️ Things to consider before going to nordschleife track.',
                        //   description: "A user-generated learning path about Things to consider before going to nordschleife track..",
                        // ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
          Topbar(
            rightIcon: CupertinoIcons.line_horizontal_3,
            rightOnTap: () {
              
            },
          )
        ],
      ),
    );
  }
}