import 'package:flutter/material.dart';
import 'package:frontend/constants/colors.dart' as appColors;
import 'package:frontend/services/services.dart';
import 'package:frontend/widgets/common/topbar.dart';
import 'package:frontend/widgets/home/empty_your_noodls.dart';
import 'package:frontend/widgets/home/generate_noodl_button.dart';
import 'package:frontend/widgets/home/heading_widget.dart';
import 'package:frontend/widgets/home/noodl_button.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    EdgeInsets dp = MediaQuery.of(context).padding;
    return Scaffold(
      backgroundColor: appColors.bgColor,
      body: Stack(
        children: [
          SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                SizedBox(height: dp.top + 60,),
                // remove this
                SizedBox(height: 12,),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 12),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      HeadingWidget(
                        heading: 'Your Noodls',
                        subHeading: 'Your learning paths appear here.'
                      ),
                      EmptyYourNoodls(),
                      SizedBox(height: 12,),
                      GenerateNoodlButton(),
                      HeadingWidget(
                        heading: 'Community Noodls',
                        subHeading: 'Community Noodls refer to popular learning paths previously generated by other users.'
                      ),
                      NoodlButton(
                        title: '🚗 Driving License in India',
                        description: "A user-generated learning path about Driving License in India.",
                      ),
                      NoodlButton(
                        title: '🥮 How to bake a chocolate chip cake without oven?',
                        description: "A user-generated learning path about how to bake a chocolate chip cake without oven?.",
                      ),
                      NoodlButton(
                        title: '🏁 Things to consider before going to n\u00fcrburgring track.',
                        description: "A user-generated learning path about Things to consider before going to n\u00fcrburgring track..",
                      ),
                      NoodlButton(
                        title: '🌱 How is Photosynthesis done?',
                        description: "A user-generated learning path about How is Photosynthesis done?.",
                      ),
                      NoodlButton(
                        title: '🏎️ Things to consider before going to nordschleife track.',
                        description: "A user-generated learning path about Things to consider before going to nordschleife track..",
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          Topbar()
        ],
      ),
    );
  }
}