// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDbNIHxmziPWX5ykmbh43tOjPy0P_deMU',
    appId: '1:284170229647:web:8e41a7219535d4c5c49dfa',
    messagingSenderId: '284170229647',
    projectId: 'noodl-a8d5f',
    authDomain: 'noodl-a8d5f.firebaseapp.com',
    storageBucket: 'noodl-a8d5f.firebasestorage.app',
    measurementId: 'G-CCCHGS6KJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwfj77Cc32kSy24WXowWFHVIplpf9ZIsA',
    appId: '1:284170229647:android:ebe40d7c18203acdc49dfa',
    messagingSenderId: '284170229647',
    projectId: 'noodl-a8d5f',
    storageBucket: 'noodl-a8d5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlld3TIdXTI-6EOFL3uIlOVxQhw-H-9m8',
    appId: '1:284170229647:ios:5be9cad9e72d06a5c49dfa',
    messagingSenderId: '284170229647',
    projectId: 'noodl-a8d5f',
    storageBucket: 'noodl-a8d5f.firebasestorage.app',
    iosClientId: '284170229647-k7vohks1h0vnh35dokmftn568eegh8f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlld3TIdXTI-6EOFL3uIlOVxQhw-H-9m8',
    appId: '1:284170229647:ios:5be9cad9e72d06a5c49dfa',
    messagingSenderId: '284170229647',
    projectId: 'noodl-a8d5f',
    storageBucket: 'noodl-a8d5f.firebasestorage.app',
    iosClientId: '284170229647-k7vohks1h0vnh35dokmftn568eegh8f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDbNIHxmziPWX5ykmbh43tOjPy0P_deMU',
    appId: '1:284170229647:web:cef040f080ea73b4c49dfa',
    messagingSenderId: '284170229647',
    projectId: 'noodl-a8d5f',
    authDomain: 'noodl-a8d5f.firebaseapp.com',
    storageBucket: 'noodl-a8d5f.firebasestorage.app',
    measurementId: 'G-508S8XZK2G',
  );

}